#!/bin/bash

## Copyright (C) 2019 - 2019 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

if [ -f /usr/lib/helper-scripts/pre.bsh ]; then
   source /usr/lib/helper-scripts/pre.bsh
fi

set -e

modprobe p_lkrg

if lsmod | grep -q vbox ; then
   virtualbox_detected=true
fi

if command -v vboxmanage &>/dev/null ; then
   virtualbox_detected=true
fi

if [ "$virtualbox_detected" = "true" ]; then
   ## https://forums.whonix.org/t/linux-kernel-runtime-guard-lkrg-linux-kernel-runtime-integrity-checking-and-exploit-detection/8477/32
   ## https://www.openwall.com/lists/lkrg-users/2020/01/24/2
   sysctl -w lkrg.enforce_msr=0 lkrg.enforce_pcfi=1
fi
